require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Naming/MethodParameterName:
  Enabled: false
RSpec/FilePath:
  Exclude:
    - spec/sqlite3_extend_function_spec.rb
RSpec/NamedSubject:
  Enabled: false
